[[extends]]
file = "../iroh-defaults.toml"

[sim]
name     = "iroh-2to10-relay-only"
topology = "2to10-relay"

[[step]]
use  = "relay-setup"
vars = { device = "relay" }

[[step]]
use    = "transfer-provider"
id     = "provider"
device = "provider"
requires = ["relay.ready"]
args     = ["--env", "dev", "--relay-only",
            "--relay-url", "https://$NETSIM_IP_relay:3340"]

[[step]]
use    = "transfer-fetcher"
id     = "fetcher-0"
device = "fetcher-0"
args   = ["${provider-0.endpoint_id}",
          "--env", "dev", "--relay-only",
          "--size=1G",
          "--relay-url",        "https://$NETSIM_IP_relay:3340",
          "--remote-relay-url", "https://$NETSIM_IP_relay:3340",
          "--remote-direct-address", "${provider-0.direct_addr}"]

[[step]]
use    = "transfer-fetcher"
id     = "fetcher-1"
device = "fetcher-1"
args   = ["${provider-1.endpoint_id}",
          "--env", "dev", "--relay-only",
          "--size=1G",
          "--relay-url",        "https://$NETSIM_IP_relay:3340",
          "--remote-relay-url", "https://$NETSIM_IP_relay:3340",
          "--remote-direct-address", "${provider-1.direct_addr}"]

[[step]]
use    = "transfer-fetcher"
id     = "fetcher-2"
device = "fetcher-2"
args   = ["${provider-0.endpoint_id}",
          "--env", "dev", "--relay-only",
          "--size=1G",
          "--relay-url",        "https://$NETSIM_IP_relay:3340",
          "--remote-relay-url", "https://$NETSIM_IP_relay:3340",
          "--remote-direct-address", "${provider-0.direct_addr}"]

[[step]]
use    = "transfer-fetcher"
id     = "fetcher-3"
device = "fetcher-3"
args   = ["${provider-1.endpoint_id}",
          "--env", "dev", "--relay-only",
          "--size=1G",
          "--relay-url",        "https://$NETSIM_IP_relay:3340",
          "--remote-relay-url", "https://$NETSIM_IP_relay:3340",
          "--remote-direct-address", "${provider-1.direct_addr}"]

[[step]]
use    = "transfer-fetcher"
id     = "fetcher-4"
device = "fetcher-4"
args   = ["${provider-0.endpoint_id}",
          "--env", "dev", "--relay-only",
          "--size=1G",
          "--relay-url",        "https://$NETSIM_IP_relay:3340",
          "--remote-relay-url", "https://$NETSIM_IP_relay:3340",
          "--remote-direct-address", "${provider-0.direct_addr}"]

[[step]]
use    = "transfer-fetcher"
id     = "fetcher-5"
device = "fetcher-5"
args   = ["${provider-1.endpoint_id}",
          "--env", "dev", "--relay-only",
          "--size=1G",
          "--relay-url",        "https://$NETSIM_IP_relay:3340",
          "--remote-relay-url", "https://$NETSIM_IP_relay:3340",
          "--remote-direct-address", "${provider-1.direct_addr}"]

[[step]]
use    = "transfer-fetcher"
id     = "fetcher-6"
device = "fetcher-6"
args   = ["${provider-0.endpoint_id}",
          "--env", "dev", "--relay-only",
          "--size=1G",
          "--relay-url",        "https://$NETSIM_IP_relay:3340",
          "--remote-relay-url", "https://$NETSIM_IP_relay:3340",
          "--remote-direct-address", "${provider-0.direct_addr}"]

[[step]]
use    = "transfer-fetcher"
id     = "fetcher-7"
device = "fetcher-7"
args   = ["${provider-1.endpoint_id}",
          "--env", "dev", "--relay-only",
          "--size=1G",
          "--relay-url",        "https://$NETSIM_IP_relay:3340",
          "--remote-relay-url", "https://$NETSIM_IP_relay:3340",
          "--remote-direct-address", "${provider-1.direct_addr}"]

[[step]]
use    = "transfer-fetcher"
id     = "fetcher-8"
device = "fetcher-8"
args   = ["${provider-0.endpoint_id}",
          "--env", "dev", "--relay-only",
          "--size=1G",
          "--relay-url",        "https://$NETSIM_IP_relay:3340",
          "--remote-relay-url", "https://$NETSIM_IP_relay:3340",
          "--remote-direct-address", "${provider-0.direct_addr}"]

[[step]]
use    = "transfer-fetcher"
id     = "fetcher-9"
device = "fetcher-9"
args   = ["${provider-1.endpoint_id}",
          "--env", "dev", "--relay-only",
          "--size=1G",
          "--relay-url",        "https://$NETSIM_IP_relay:3340",
          "--remote-relay-url", "https://$NETSIM_IP_relay:3340",
          "--remote-direct-address", "${provider-1.direct_addr}"]

[[step]]
action  = "wait-for"
id      = "fetcher-0"
timeout = "120s"

[[step]]
action  = "wait-for"
id      = "fetcher-1"
timeout = "120s"

[[step]]
action  = "wait-for"
id      = "fetcher-2"
timeout = "120s"

[[step]]
action  = "wait-for"
id      = "fetcher-3"
timeout = "120s"

[[step]]
action  = "wait-for"
id      = "fetcher-4"
timeout = "120s"

[[step]]
action  = "wait-for"
id      = "fetcher-5"
timeout = "120s"

[[step]]
action  = "wait-for"
id      = "fetcher-6"
timeout = "120s"

[[step]]
action  = "wait-for"
id      = "fetcher-7"
timeout = "120s"

[[step]]
action  = "wait-for"
id      = "fetcher-8"
timeout = "120s"

[[step]]
action  = "wait-for"
id      = "fetcher-9"
timeout = "120s"

[[step]]
action = "assert"
checks = [
  "fetcher-0.size matches [0-9]+",
  "fetcher-1.size matches [0-9]+",
  "fetcher-2.size matches [0-9]+",
  "fetcher-3.size matches [0-9]+",
  "fetcher-4.size matches [0-9]+",
  "fetcher-5.size matches [0-9]+",
  "fetcher-6.size matches [0-9]+",
  "fetcher-7.size matches [0-9]+",
  "fetcher-8.size matches [0-9]+",
  "fetcher-9.size matches [0-9]+",
]
