# Allow-list for `cargo-check-external-types`.
#
# Used by the `check_external_types` CI job to enforce
# https://github.com/n0-computer/iroh/issues/3177: each foreign type in the
# public API blocks a semver-breaking update of that crate during 1.0, so we
# keep this list as small as possible.

allowed_external_types = [
    # workspace crates
    "iroh_base::*",
    "iroh_dns::*",
    "iroh_relay::*",

    # 1.0 crates that we deem fine to be part of the public API
    "bytes::*",
    "http::*",
    "http_body::*",
    "hyper::*",
    "rustls_pki_types::*",
    "serde::*",
    "serde_core::*",
    "tokio::*",
    "url::*",

    # crates owned by us that will move to 1.0 as well
    "iroh_metrics::*",
    "n0_error::*",
    "n0_watcher::*",
    "noq::*",
    "noq_proto::*",
    "noq_udp::*",
    "portmapper::metrics::Metrics",

    # non-1.0 crates that we decided to accept in the public API
    "rustls::*",
    "tokio_rustls::*",
    "futures_core::stream::Stream",
    "futures_sink::Sink",
    # these are only type aliases
    "futures_lite::future::Boxed",
    "futures_lite::stream::Boxed",
]
