// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(Iroh)
    import Iroh
#endif

private extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_iroh_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_iroh_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_PANIC: Int8 = 2

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: nil)
}

private func rustCallWithError<T>(
    _ errorHandler: @escaping (RustBuffer) throws -> Error,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T
) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> Error)?
) throws {
    switch callStatus.code {
    case CALL_SUCCESS:
        return

    case CALL_ERROR:
        if let errorHandler = errorHandler {
            throw try errorHandler(callStatus.errorBuf)
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.unexpectedRustCallError
        }

    case CALL_PANIC:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

// Public interface members begin here.

private struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

private struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return try Data(bytes: readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}

public protocol AuthorIdProtocol {
    func toString() -> String
}

public class AuthorId: AuthorIdProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_iroh_fn_free_authorid(pointer, $0) }
    }

    public func toString() -> String {
        return try! FfiConverterString.lift(
            try!
                rustCall {
                    uniffi_iroh_fn_method_authorid_to_string(self.pointer, $0)
                }
        )
    }
}

public struct FfiConverterTypeAuthorId: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = AuthorId

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AuthorId {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: AuthorId, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> AuthorId {
        return AuthorId(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: AuthorId) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}

public func FfiConverterTypeAuthorId_lift(_ pointer: UnsafeMutableRawPointer) throws -> AuthorId {
    return try FfiConverterTypeAuthorId.lift(pointer)
}

public func FfiConverterTypeAuthorId_lower(_ value: AuthorId) -> UnsafeMutableRawPointer {
    return FfiConverterTypeAuthorId.lower(value)
}

public protocol DocProtocol {
    func id() -> String
    func shareWrite() throws -> DocTicket
    func shareRead() throws -> DocTicket
    func setBytes(author: AuthorId, key: Data, value: Data) throws -> SignedEntry
    func getContentBytes(entry: SignedEntry) throws -> Data
    func latest() throws -> [SignedEntry]
    func subscribe(cb: SubscribeCallback) throws
}

public class Doc: DocProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_iroh_fn_free_doc(pointer, $0) }
    }

    public func id() -> String {
        return try! FfiConverterString.lift(
            try!
                rustCall {
                    uniffi_iroh_fn_method_doc_id(self.pointer, $0)
                }
        )
    }

    public func shareWrite() throws -> DocTicket {
        return try FfiConverterTypeDocTicket.lift(
            rustCallWithError(FfiConverterTypeIrohError.lift) {
                uniffi_iroh_fn_method_doc_share_write(self.pointer, $0)
            }
        )
    }

    public func shareRead() throws -> DocTicket {
        return try FfiConverterTypeDocTicket.lift(
            rustCallWithError(FfiConverterTypeIrohError.lift) {
                uniffi_iroh_fn_method_doc_share_read(self.pointer, $0)
            }
        )
    }

    public func setBytes(author: AuthorId, key: Data, value: Data) throws -> SignedEntry {
        return try FfiConverterTypeSignedEntry.lift(
            rustCallWithError(FfiConverterTypeIrohError.lift) {
                uniffi_iroh_fn_method_doc_set_bytes(self.pointer,
                                                    FfiConverterTypeAuthorId.lower(author),
                                                    FfiConverterData.lower(key),
                                                    FfiConverterData.lower(value), $0)
            }
        )
    }

    public func getContentBytes(entry: SignedEntry) throws -> Data {
        return try FfiConverterData.lift(
            rustCallWithError(FfiConverterTypeIrohError.lift) {
                uniffi_iroh_fn_method_doc_get_content_bytes(self.pointer,
                                                            FfiConverterTypeSignedEntry.lower(entry), $0)
            }
        )
    }

    public func latest() throws -> [SignedEntry] {
        return try FfiConverterSequenceTypeSignedEntry.lift(
            rustCallWithError(FfiConverterTypeIrohError.lift) {
                uniffi_iroh_fn_method_doc_latest(self.pointer, $0)
            }
        )
    }

    public func subscribe(cb: SubscribeCallback) throws {
        try
            rustCallWithError(FfiConverterTypeIrohError.lift) {
                uniffi_iroh_fn_method_doc_subscribe(self.pointer,
                                                    FfiConverterCallbackInterfaceSubscribeCallback.lower(cb), $0)
            }
    }
}

public struct FfiConverterTypeDoc: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = Doc

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Doc {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: Doc, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> Doc {
        return Doc(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: Doc) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}

public func FfiConverterTypeDoc_lift(_ pointer: UnsafeMutableRawPointer) throws -> Doc {
    return try FfiConverterTypeDoc.lift(pointer)
}

public func FfiConverterTypeDoc_lower(_ value: Doc) -> UnsafeMutableRawPointer {
    return FfiConverterTypeDoc.lower(value)
}

public protocol DocTicketProtocol {
    func toString() -> String
}

public class DocTicket: DocTicketProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_iroh_fn_free_docticket(pointer, $0) }
    }

    public static func fromString(content: String) throws -> DocTicket {
        return try DocTicket(unsafeFromRawPointer: rustCallWithError(FfiConverterTypeIrohError.lift) {
            uniffi_iroh_fn_constructor_docticket_from_string(
                FfiConverterString.lower(content), $0
            )
        })
    }

    public func toString() -> String {
        return try! FfiConverterString.lift(
            try!
                rustCall {
                    uniffi_iroh_fn_method_docticket_to_string(self.pointer, $0)
                }
        )
    }
}

public struct FfiConverterTypeDocTicket: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = DocTicket

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DocTicket {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: DocTicket, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> DocTicket {
        return DocTicket(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: DocTicket) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}

public func FfiConverterTypeDocTicket_lift(_ pointer: UnsafeMutableRawPointer) throws -> DocTicket {
    return try FfiConverterTypeDocTicket.lift(pointer)
}

public func FfiConverterTypeDocTicket_lower(_ value: DocTicket) -> UnsafeMutableRawPointer {
    return FfiConverterTypeDocTicket.lower(value)
}

public protocol IrohNodeProtocol {
    func peerId() -> String
    func createDoc() throws -> Doc
    func importDoc(ticket: DocTicket) throws -> Doc
    func createAuthor() throws -> AuthorId
    func stats() throws -> [String: CounterStats]
}

public class IrohNode: IrohNodeProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    public convenience init() throws {
        try self.init(unsafeFromRawPointer: rustCallWithError(FfiConverterTypeIrohError.lift) {
            uniffi_iroh_fn_constructor_irohnode_new($0)
        })
    }

    deinit {
        try! rustCall { uniffi_iroh_fn_free_irohnode(pointer, $0) }
    }

    public func peerId() -> String {
        return try! FfiConverterString.lift(
            try!
                rustCall {
                    uniffi_iroh_fn_method_irohnode_peer_id(self.pointer, $0)
                }
        )
    }

    public func createDoc() throws -> Doc {
        return try FfiConverterTypeDoc.lift(
            rustCallWithError(FfiConverterTypeIrohError.lift) {
                uniffi_iroh_fn_method_irohnode_create_doc(self.pointer, $0)
            }
        )
    }

    public func importDoc(ticket: DocTicket) throws -> Doc {
        return try FfiConverterTypeDoc.lift(
            rustCallWithError(FfiConverterTypeIrohError.lift) {
                uniffi_iroh_fn_method_irohnode_import_doc(self.pointer,
                                                          FfiConverterTypeDocTicket.lower(ticket), $0)
            }
        )
    }

    public func createAuthor() throws -> AuthorId {
        return try FfiConverterTypeAuthorId.lift(
            rustCallWithError(FfiConverterTypeIrohError.lift) {
                uniffi_iroh_fn_method_irohnode_create_author(self.pointer, $0)
            }
        )
    }

    public func stats() throws -> [String: CounterStats] {
        return try FfiConverterDictionaryStringTypeCounterStats.lift(
            rustCallWithError(FfiConverterTypeIrohError.lift) {
                uniffi_iroh_fn_method_irohnode_stats(self.pointer, $0)
            }
        )
    }
}

public struct FfiConverterTypeIrohNode: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = IrohNode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IrohNode {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: IrohNode, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> IrohNode {
        return IrohNode(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: IrohNode) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}

public func FfiConverterTypeIrohNode_lift(_ pointer: UnsafeMutableRawPointer) throws -> IrohNode {
    return try FfiConverterTypeIrohNode.lift(pointer)
}

public func FfiConverterTypeIrohNode_lower(_ value: IrohNode) -> UnsafeMutableRawPointer {
    return FfiConverterTypeIrohNode.lower(value)
}

public protocol SignedEntryProtocol {
    func author() -> AuthorId
    func key() -> Data
}

public class SignedEntry: SignedEntryProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { uniffi_iroh_fn_free_signedentry(pointer, $0) }
    }

    public func author() -> AuthorId {
        return try! FfiConverterTypeAuthorId.lift(
            try!
                rustCall {
                    uniffi_iroh_fn_method_signedentry_author(self.pointer, $0)
                }
        )
    }

    public func key() -> Data {
        return try! FfiConverterData.lift(
            try!
                rustCall {
                    uniffi_iroh_fn_method_signedentry_key(self.pointer, $0)
                }
        )
    }
}

public struct FfiConverterTypeSignedEntry: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SignedEntry

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignedEntry {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SignedEntry, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SignedEntry {
        return SignedEntry(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SignedEntry) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}

public func FfiConverterTypeSignedEntry_lift(_ pointer: UnsafeMutableRawPointer) throws -> SignedEntry {
    return try FfiConverterTypeSignedEntry.lift(pointer)
}

public func FfiConverterTypeSignedEntry_lower(_ value: SignedEntry) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSignedEntry.lower(value)
}

public struct CounterStats {
    public var value: UInt64
    public var description: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(value: UInt64, description: String) {
        self.value = value
        self.description = description
    }
}

extension CounterStats: Equatable, Hashable {
    public static func == (lhs: CounterStats, rhs: CounterStats) -> Bool {
        if lhs.value != rhs.value {
            return false
        }
        if lhs.description != rhs.description {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(value)
        hasher.combine(description)
    }
}

public struct FfiConverterTypeCounterStats: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CounterStats {
        return try CounterStats(
            value: FfiConverterUInt64.read(from: &buf),
            description: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: CounterStats, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.value, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
    }
}

public func FfiConverterTypeCounterStats_lift(_ buf: RustBuffer) throws -> CounterStats {
    return try FfiConverterTypeCounterStats.lift(buf)
}

public func FfiConverterTypeCounterStats_lower(_ value: CounterStats) -> RustBuffer {
    return FfiConverterTypeCounterStats.lower(value)
}

public enum IrohError {
    case Runtime(description: String)
    case NodeCreate(description: String)
    case Doc(description: String)
    case Author(description: String)
    case DocTicket(description: String)
    case Uniffi(description: String)

    fileprivate static func uniffiErrorHandler(_ error: RustBuffer) throws -> Error {
        return try FfiConverterTypeIrohError.lift(error)
    }
}

public struct FfiConverterTypeIrohError: FfiConverterRustBuffer {
    typealias SwiftType = IrohError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> IrohError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .Runtime(
                description: FfiConverterString.read(from: &buf)
            )
        case 2: return try .NodeCreate(
                description: FfiConverterString.read(from: &buf)
            )
        case 3: return try .Doc(
                description: FfiConverterString.read(from: &buf)
            )
        case 4: return try .Author(
                description: FfiConverterString.read(from: &buf)
            )
        case 5: return try .DocTicket(
                description: FfiConverterString.read(from: &buf)
            )
        case 6: return try .Uniffi(
                description: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: IrohError, into buf: inout [UInt8]) {
        switch value {
        case let .Runtime(description):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(description, into: &buf)

        case let .NodeCreate(description):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(description, into: &buf)

        case let .Doc(description):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(description, into: &buf)

        case let .Author(description):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(description, into: &buf)

        case let .DocTicket(description):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(description, into: &buf)

        case let .Uniffi(description):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(description, into: &buf)
        }
    }
}

extension IrohError: Equatable, Hashable {}

extension IrohError: Error {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
public enum LiveEvent {
    case insertLocal
    case insertRemote
}

public struct FfiConverterTypeLiveEvent: FfiConverterRustBuffer {
    typealias SwiftType = LiveEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LiveEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return .insertLocal

        case 2: return .insertRemote

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: LiveEvent, into buf: inout [UInt8]) {
        switch value {
        case .insertLocal:
            writeInt(&buf, Int32(1))

        case .insertRemote:
            writeInt(&buf, Int32(2))
        }
    }
}

public func FfiConverterTypeLiveEvent_lift(_ buf: RustBuffer) throws -> LiveEvent {
    return try FfiConverterTypeLiveEvent.lift(buf)
}

public func FfiConverterTypeLiveEvent_lower(_ value: LiveEvent) -> RustBuffer {
    return FfiConverterTypeLiveEvent.lower(value)
}

extension LiveEvent: Equatable, Hashable {}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private typealias UniFFICallbackHandle = UInt64
private class UniFFICallbackHandleMap<T> {
    private var leftMap: [UniFFICallbackHandle: T] = [:]
    private var counter: [UniFFICallbackHandle: UInt64] = [:]
    private var rightMap: [ObjectIdentifier: UniFFICallbackHandle] = [:]

    private let lock = NSLock()
    private var currentHandle: UniFFICallbackHandle = 0
    private let stride: UniFFICallbackHandle = 1

    func insert(obj: T) -> UniFFICallbackHandle {
        lock.withLock {
            let id = ObjectIdentifier(obj as AnyObject)
            let handle = rightMap[id] ?? {
                currentHandle += stride
                let handle = currentHandle
                leftMap[handle] = obj
                rightMap[id] = handle
                return handle
            }()
            counter[handle] = (counter[handle] ?? 0) + 1
            return handle
        }
    }

    func get(handle: UniFFICallbackHandle) -> T? {
        lock.withLock {
            leftMap[handle]
        }
    }

    func delete(handle: UniFFICallbackHandle) {
        remove(handle: handle)
    }

    @discardableResult
    func remove(handle: UniFFICallbackHandle) -> T? {
        lock.withLock {
            defer { counter[handle] = (counter[handle] ?? 1) - 1 }
            guard counter[handle] == 1 else { return leftMap[handle] }
            let obj = leftMap.removeValue(forKey: handle)
            if let obj = obj {
                rightMap.removeValue(forKey: ObjectIdentifier(obj as AnyObject))
            }
            return obj
        }
    }
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Declaration and FfiConverters for SubscribeCallback Callback Interface

public protocol SubscribeCallback: AnyObject {
    func event(event: LiveEvent) throws
}

// The ForeignCallback that is passed to Rust.
private let foreignCallbackCallbackInterfaceSubscribeCallback: ForeignCallback =
    { (handle: UniFFICallbackHandle, method: Int32, argsData: UnsafePointer<UInt8>, argsLen: Int32, out_buf: UnsafeMutablePointer<RustBuffer>) -> Int32 in

        func invokeEvent(_ swiftCallbackInterface: SubscribeCallback, _ argsData: UnsafePointer<UInt8>, _ argsLen: Int32, _ out_buf: UnsafeMutablePointer<RustBuffer>) throws -> Int32 {
            var reader = createReader(data: Data(bytes: argsData, count: Int(argsLen)))
            func makeCall() throws -> Int32 {
                try swiftCallbackInterface.event(
                    event: FfiConverterTypeLiveEvent.read(from: &reader)
                )
                return UNIFFI_CALLBACK_SUCCESS
            }
            do {
                return try makeCall()
            } catch let error as IrohError {
                out_buf.pointee = FfiConverterTypeIrohError.lower(error)
                return UNIFFI_CALLBACK_ERROR
            }
        }

        switch method {
        case IDX_CALLBACK_FREE:
            FfiConverterCallbackInterfaceSubscribeCallback.drop(handle: handle)
            // Sucessful return
            // See docs of ForeignCallback in `uniffi_core/src/ffi/foreigncallbacks.rs`
            return UNIFFI_CALLBACK_SUCCESS
        case 1:
            let cb: SubscribeCallback
            do {
                cb = try FfiConverterCallbackInterfaceSubscribeCallback.lift(handle)
            } catch {
                out_buf.pointee = FfiConverterString.lower("SubscribeCallback: Invalid handle")
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }
            do {
                return try invokeEvent(cb, argsData, argsLen, out_buf)
            } catch {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return UNIFFI_CALLBACK_UNEXPECTED_ERROR
            }

        // This should never happen, because an out of bounds method index won't
        // ever be used. Once we can catch errors, we should return an InternalError.
        // https://github.com/mozilla/uniffi-rs/issues/351
        default:
            // An unexpected error happened.
            // See docs of ForeignCallback in `uniffi_core/src/ffi/foreigncallbacks.rs`
            return UNIFFI_CALLBACK_UNEXPECTED_ERROR
        }
    }

// FfiConverter protocol for callback interfaces
private enum FfiConverterCallbackInterfaceSubscribeCallback {
    private static let initCallbackOnce: () = {
        // Swift ensures this initializer code will once run once, even when accessed by multiple threads.
        try! rustCall { (err: UnsafeMutablePointer<RustCallStatus>) in
            uniffi_iroh_fn_init_callback_subscribecallback(foreignCallbackCallbackInterfaceSubscribeCallback, err)
        }
    }()

    private static func ensureCallbackinitialized() {
        _ = initCallbackOnce
    }

    static func drop(handle: UniFFICallbackHandle) {
        handleMap.remove(handle: handle)
    }

    private static var handleMap = UniFFICallbackHandleMap<SubscribeCallback>()
}

extension FfiConverterCallbackInterfaceSubscribeCallback: FfiConverter {
    typealias SwiftType = SubscribeCallback
    // We can use Handle as the FfiType because it's a typealias to UInt64
    typealias FfiType = UniFFICallbackHandle

    public static func lift(_ handle: UniFFICallbackHandle) throws -> SwiftType {
        ensureCallbackinitialized()
        guard let callback = handleMap.get(handle: handle) else {
            throw UniffiInternalError.unexpectedStaleHandle
        }
        return callback
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        ensureCallbackinitialized()
        let handle: UniFFICallbackHandle = try readInt(&buf)
        return try lift(handle)
    }

    public static func lower(_ v: SwiftType) -> UniFFICallbackHandle {
        ensureCallbackinitialized()
        return handleMap.insert(obj: v)
    }

    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        ensureCallbackinitialized()
        writeInt(&buf, lower(v))
    }
}

private struct FfiConverterSequenceTypeSignedEntry: FfiConverterRustBuffer {
    typealias SwiftType = [SignedEntry]

    public static func write(_ value: [SignedEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSignedEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SignedEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [SignedEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeSignedEntry.read(from: &buf))
        }
        return seq
    }
}

private struct FfiConverterDictionaryStringTypeCounterStats: FfiConverterRustBuffer {
    public static func write(_ value: [String: CounterStats], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterTypeCounterStats.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: CounterStats] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: CounterStats]()
        dict.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterTypeCounterStats.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}

// Use a global variables to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 22
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_iroh_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if uniffi_iroh_checksum_method_irohnode_peer_id() != 46487 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_method_irohnode_create_doc() != 22030 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_method_irohnode_import_doc() != 37728 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_method_irohnode_create_author() != 12072 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_method_irohnode_stats() != 12801 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_method_doc_id() != 34918 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_method_doc_share_write() != 64425 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_method_doc_share_read() != 8947 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_method_doc_set_bytes() != 3381 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_method_doc_get_content_bytes() != 11221 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_method_doc_latest() != 41807 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_method_doc_subscribe() != 17522 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_method_authorid_to_string() != 61926 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_method_signedentry_author() != 26724 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_method_signedentry_key() != 11515 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_method_docticket_to_string() != 32683 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_constructor_irohnode_new() != 18953 {
        return InitializationResult.apiChecksumMismatch
    }
    if uniffi_iroh_checksum_constructor_docticket_from_string() != 12688 {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}
