/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_LIBIROH__
#define __RUST_LIBIROH__

#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

int32_t add_numbers (
    int32_t number1,
    int32_t number2);

uint32_t get_ticket (
    char const * ticket,
    char const * out_path);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __RUST_LIBIROH__ */
