/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_IROH_FFI__
#define __RUST_IROH_FFI__

#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

uint32_t iroh_get (
    char const * hash,
    char const * peer,
    char const * peer_addr,
    char const * out_path);

uint32_t iroh_get_ticket (
    char const * ticket,
    char const * out_path);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __RUST_IROH_FFI__ */
