#!/usr/bin/env bash
set -euo pipefail

# local-relay-setup.sh
# Helper script to bootstrap a local iroh-relay with QUIC Address Discovery.
# Generates self-signed TLS cert (with SAN), relay config, client config, and run hints.
# Safe to re-run; existing certs/configs are left intact unless --force is passed.

FORCE=0
CERT_DIR=tmp/certs
RELAY_CFG=tmp/iroh-relay.config.toml
CLIENT_CFG=iroh.config.toml
RELAY_HTTP_PORT=3340
RELAY_METRICS_PORT=9090
RELAY_QUIC_PORT=7842

while [[ ${1:-} != "" ]]; do
  case "$1" in
    --force) FORCE=1 ; shift ;;
    --cert-dir) CERT_DIR="$2" ; shift 2 ;;
    --relay-config) RELAY_CFG="$2" ; shift 2 ;;
    --client-config) CLIENT_CFG="$2" ; shift 2 ;;
    --http-port) RELAY_HTTP_PORT="$2" ; shift 2 ;;
    --metrics-port) RELAY_METRICS_PORT="$2" ; shift 2 ;;
    --quic-port) RELAY_QUIC_PORT="$2" ; shift 2 ;;
    -h|--help)
      grep '^#' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

mkdir -p "$CERT_DIR" tmp

CERT_PEM="$CERT_DIR/cert.pem"
KEY_PEM="$CERT_DIR/cert.key.pem"

if [[ $FORCE -eq 1 ]]; then
  rm -f "$CERT_PEM" "$KEY_PEM"
fi

if [[ ! -f "$CERT_PEM" || ! -f "$KEY_PEM" ]]; then
  echo "Generating self-signed certificate with SAN (localhost, loopback IPs)" >&2
  openssl req -x509 -newkey rsa:2048 -nodes \
    -keyout "$KEY_PEM" -out "$CERT_PEM" \
    -days 365 -subj "/CN=localhost" \
    -addext "subjectAltName=DNS:localhost,IP:127.0.0.1,IP:::1"
else
  echo "Reusing existing certs in $CERT_DIR" >&2
fi

if [[ $FORCE -eq 1 ]]; then
  rm -f "$RELAY_CFG" "$CLIENT_CFG"
fi

if [[ ! -f "$RELAY_CFG" ]]; then
  cat > "$RELAY_CFG" <<EOF
# Auto-generated by scripts/local-relay-setup.sh
# QUIC Address Discovery enabled; manual TLS configured.
enable_quic_addr_discovery = true

[tls]
cert_path = "$CERT_PEM"
key_path  = "$KEY_PEM"

[listen]
# These keys are illustrative; adjust if iroh-relay supports explicit settings.
# http_addr = "127.0.0.1:${RELAY_HTTP_PORT}"
# metrics_addr = "127.0.0.1:${RELAY_METRICS_PORT}"
# quic_addr = "0.0.0.0:${RELAY_QUIC_PORT}"
EOF
  echo "Wrote relay config: $RELAY_CFG" >&2
else
  echo "Relay config exists: $RELAY_CFG" >&2
fi

if [[ ! -f "$CLIENT_CFG" ]]; then
  cat > "$CLIENT_CFG" <<EOF
# Auto-generated client relay preference
[[relays]]
url = "http://localhost:${RELAY_HTTP_PORT}"
EOF
  echo "Wrote client config: $CLIENT_CFG" >&2
else
  echo "Client config exists: $CLIENT_CFG" >&2
fi

echo
cat <<INFO
Next steps:
1. Build relay: cargo build -p iroh-relay
2. Run relay (dev mode with verbose logs):
   RUST_LOG='info,iroh_relay=debug,iroh_relay::quic=trace,iroh::net_report=trace,quinn=info,rustls=info' \
     target/debug/iroh-relay --config-path $RELAY_CFG --dev | tee tmp/relay.log
3. Run examples (transfer, listen-unreliable, connect-unreliable) as per docs/local-relay-dev.md
4. Troubleshooting: see docs/local-relay-dev.md#troubleshooting

Re-run with --force to regenerate artifacts.
INFO
